version: "3.9"

services:
  ai-service:
    build: .
    container_name: ai-generator
    env_file:
      - .env
    ports:
      - "${GENERATOR_APP_HOST_PORT}:${GENERATOR_APP_CONTAINER_PORT}"
    volumes:
      - ./files:/app/files
    restart: unless-stopped
    networks:
      - shared-net

networks:
  shared-net:
    external: true